export { type IResponse } from "./IResponse";
export { type IListMovie } from "./IListMovie";
export { type IGenre } from "./IGenre";
export { type IGenresResponse } from "./IGenre";
export { type IParams } from "./IParams";
export { type IMovie } from "./IMovie";
export { type IVideo } from "./IVideo";
export { type ICast } from "./ICast";
export { type IImage } from "./IImage";